name: logger_plus
description: This package is for logging. Using this package you can see the console message on the phone screen by shaking your phone.
version: 0.0.6+4
homepage: https://github.com/DevendraFlutterDev/logger_plus

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  sensors_plus: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
